---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
  - name: Start clickhouse service
    become: true
    ansible.builtin.service:
      name: clickhouse-server
      state: restarted
  tasks:
  - name: Add clickhouse GPG key
    become: true
    ansible.builtin.apt_key:
      keyserver: keyserver.ubuntu.com
      id: 8919F6BD2B48D754
  - name: Add clickhouse repo
    become: true
    ansible.builtin.apt_repository:
      repo: deb https://packages.clickhouse.com/deb stable main
      state: present
  - name: Install clickhouse packages
    become: true
    ansible.builtin.apt:
      pkg:
      - "clickhouse-client={{ clickhouse_version }}"
      - "clickhouse-server={{ clickhouse_version }}"
      - "clickhouse-common-static={{ clickhouse_version }}"
      state: present
      update_cache: true
    notify: Start clickhouse service
  - name: Flush handlers
    meta: flush_handlers
  - name: Create database
    ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
    register: create_db
    failed_when: create_db.rc != 0 and create_db.rc !=82
    changed_when: create_db.rc == 0

- name: Install Vector
  hosts: clickhouse
  tasks:
  - name: Download Vector archive
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "./vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
  - name: Create directory for Vector
    become: true
    ansible.builtin.file:
      path: "/opt/vector"
      state: directory
      mode: "0777"
  - name: Extract Vector archive
    ansible.builtin.unarchive:
      src: "~/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
      dest: "/opt/vector"
      extra_opts: [--strip-components=2]
      remote_src: yes
      creates: "/opt/vector/config"
  - name: Build Vector config
    ansible.builtin.template:
      src: vector.toml.tpl
      dest: "{{ vector_config_file }}"
