---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: ubuntu
  vars:
    clickhouse_dbs_custom:
      - { name: test1 }
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  remote_user: ubuntu
  vars:
    vector_version: latest
  roles:
    - vector

- name: Install Lighthouse
  hosts: lighthouse
  remote_user: ubuntu
  roles:
    - lighthouse
